"""Generate VelaGuard GB2312 + ASCII LVGL font using existing local Noto.
Dependencies: Pillow and fontTools. No network; no LVGL/upstream modifications.
"""
from pathlib import Path
import hashlib
from PIL import ImageFont
from fontTools.ttLib import TTFont

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT.parent/'apps/graphics/lvgl/lvgl/tests/src/test_files/fonts/noto'
font_path=SOURCE/'NotoSansSC-Regular.ttf'
codepoints=set(range(32,127))
for a in range(0xa1,0xf8):
    for b in range(0xa1,0xff):
        try: codepoints.add(ord(bytes((a,b)).decode('gb2312')))
        except UnicodeDecodeError: pass
codepoints=sorted(codepoints)
with TTFont(font_path) as source:
    assert not set(codepoints)-set(source.getBestCmap()), 'Source missing requested glyphs'
font=ImageFont.truetype(str(font_path),16)
ascent,descent=font.getmetrics()
bitmap=bytearray(); descriptors=[(0,0,0,0,0,0)]
for cp in codepoints:
    mask,(x,y)=font.getmask2(chr(cp),mode='L',anchor='ls')
    width,height=mask.size
    advance=round(font.getlength(chr(cp))*16)
    assert 0<=advance<4096 and width<256 and height<256 and -128<=x<=127 and -128<=-y-height<=127
    descriptors.append((len(bitmap),advance,width,height,x,-y-height))
    levels=[(v*15+127)//255 for v in bytes(mask)]
    if len(levels)%2:levels.append(0)
    bitmap.extend((levels[i]<<4)|levels[i+1] for i in range(0,len(levels),2))
assert len(bitmap)<1<<20 and len(codepoints)==7540
assert codepoints[-1]-32+1<=65535
lines=['/* Generated by tools/generate_font_cn.py; SIL OFL 1.1.',
       ' * Source copyright/license: ../fonts/OFL-Noto.txt.',
       ' * Source SHA256: '+hashlib.sha256(font_path.read_bytes()).hexdigest()+' */',
       '#include <lvgl/lvgl.h>',
       'static const uint8_t glyph_bitmap[] = {']
for i in range(0,len(bitmap),24):lines.append(','.join('0x%02x'%v for v in bitmap[i:i+24])+',')
lines+=['};','static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {']
lines+=['{'+','.join(map(str,d))+'},' for d in descriptors]
lines+=['};','static const uint16_t unicode_list[] = {']
for i in range(0,len(codepoints),16):lines.append(','.join('0x%04x'%(cp-32) for cp in codepoints[i:i+16])+',')
lines+=['};','static const lv_font_fmt_txt_cmap_t cmaps[] = {',
        '{.range_start=32,.range_length=%d,.glyph_id_start=1,'% (codepoints[-1]-32+1),
        '.unicode_list=unicode_list,.glyph_id_ofs_list=NULL,.list_length=%d,'%len(codepoints),
        '.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}};',
        'static const lv_font_fmt_txt_dsc_t font_dsc = {',
        '.glyph_bitmap=glyph_bitmap,.glyph_dsc=glyph_dsc,.cmaps=cmaps,',
        '.kern_dsc=NULL,.kern_scale=0,.cmap_num=1,.bpp=4,.kern_classes=0,.bitmap_format=0};',
        'const lv_font_t velaguard_font_cn16 = {',
        '.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,',
        '.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,',
        '.line_height = %d, .base_line = %d,'%(ascent+descent,descent),
        '.subpx=LV_FONT_SUBPX_NONE,.underline_position=-2,.underline_thickness=1,.dsc=&font_dsc};','']
output=ROOT/'app/velaguard/src/velaguard_font_cn16.c'
output.write_text('\n'.join(lines),encoding='utf-8')
license_dir=ROOT/'app/velaguard/fonts';license_dir.mkdir(exist_ok=True)
(license_dir/'OFL-Noto.txt').write_bytes((SOURCE/'OFL.txt').read_bytes())
print('Generated glyphs=%d bitmap=%d source_bytes=%d line=%d baseline=%d'%(len(codepoints),len(bitmap),output.stat().st_size,ascent+descent,descent))
